title: Collected Prayers
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Collections
collections_dir: collections
collections:
  pages:
    output: true
    permalink: /:title
  prayers:
    output: true
    permalink: /prayers/:title


defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: 
  - scope:
      path: ""
      type: prayers
    values:
      layout: prayer
      fonts: <link href="https://fonts.googleapis.com/css2?family=Source+Serif+4:ital,opsz,wght@0,8..60,200..900;1,8..60,200..900&display=swap" rel="stylesheet">
  - scope:
      path: "_prayers/early-church"
      type: prayers
    values:
      era: early
  - scope:
      path: "_prayers/reformation-church"
      type: prayers
    values:
      era: reformation
  - scope:
      path: "_prayers/modern-church"
      type: prayers
    values:
      era: modern

# Build settings
plugins:
  - jekyll-feed
  - jekyll-minifier

jekyll-minifier:
  remove_intertag_spaces: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - script/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
