bcp_1762:
  citation: >-
    The Church of England, <cite>The Book of Common Prayer...
    According to the Use of the Church of England</cite> (Cambridge, 1762)

bright_collects_1864:
  citation: >- 
    William Bright, <cite>Ancient Collects and Other Prayers, 
    Selected for Devotional Use from Various Rituals</cite> 
    (Oxford and London: J.H. and Jas. Parker, 1864)

common_worship_1906:
  citation: >-
    Presbyterian Church In The U.S.A. General Assembly and Henry Van Dyke, 
    <cite>The Book of Common Worship</cite> (Philadelphia: 
    The Presbyterian board of publication and Sabbath-school work),
    1906

fox_chain_1913:
  citation: >- 
    Selina Fitzherbert Fox, 
    <cite>A Chain of Prayers Across the Ages: Forty Centuries of Prayer</cite> 
    (Toronto: Bell Cockburn, 1913)

gelasian:
  citation: <cite><a href="https://en.wikipedia.org/wiki/Gelasian_Sacramentary">Gelasian Sacramentary</a></cite>

potts_early_1953:
  citation: >- 
    J. Manning Potts, ed., <cite>Prayers of the Early Church</cite> 
    (Nashville: Upper Room, 1953)

syrian_clementine:
  citation: <cite>Syrian Clementine Liturgy</cite>