bcp_1762:
  citation: >-
    <cite>The Book of Common Prayer...
    According to the Use of the Church of England</cite> (Cambridge, 1762) 
    by The Church of England

bright_collects_1864:
  citation: >- 
    <cite>Ancient Collects and Other Prayers, 
    Selected for Devotional Use from Various Rituals</cite> 
    (Oxford and London: J.H. and Jas. Parker, 1864) by William Bright

common_worship_1906:
  citation: >-
    <cite>The Book of Common Worship</cite> (Philadelphia: 
    The Presbyterian board of publication and Sabbath-school work, 1906)
    by Presbyterian Church In The U.S.A. General Assembly and Henry Van Dyke

fox_chain_1913:
  citation: >-  
    <cite>A Chain of Prayers Across the Ages: Forty Centuries of Prayer</cite> 
    (Toronto: Bell Cockburn, 1913) by Selina Fitzherbert Fox

gelasian:
  citation: <cite><a href="https://en.wikipedia.org/wiki/Gelasian_Sacramentary">Gelasian Sacramentary</a></cite>

potts_early_1953:
  citation: >- 
    <cite>Prayers of the Early Church</cite> 
    (Nashville: Upper Room, 1953), edited by J. Manning Potts

syrian_clementine:
  citation: <cite>Syrian Clementine Liturgy</cite>