common-worship-1906:
  title: The Book of Common Worship
  author: Presbyterian Church In The U.S.A. General Assembly and Henry Van Dyke
  pub:
    location: Philadelphia
    publisher: The Presbyterian board of publication and Sabbath-school work
    year: 1906

fox_chain_1913:
  title: "A Chain of Prayers Across the Ages: Forty Centuries of Prayer"
  author: Selina Fitzherbert Fox
  pub:
    location: Toronto
    publisher: Bell and Cockburn
    year: 1913

gelasian:
  title: Gelasian Sacramentary
  url: https://en.wikipedia.org/wiki/Gelasian_Sacramentary

potts-early-1953:
  title: Prayers of the Early Church
  author: J. Manning Potts, ed.
  pub:
    location: Nashville
    publisher: Upper Room
    year: 1953

syrian-clementine:
  title: Syrian Clementine Liturgy